package lk.ijse.CinnamonManagementSystem.util;

public enum Routes {
    CUSTOMER,EMPLOYEES,SUPPLIER,ITEM,VEHICLE,STOCK,PAYMENT_DETAILS,CUSTOMER_ORDER,CUSTOMER_ORDER_DETAILS,SUPPLIER_ORDER,SUPPLIER_ORDER_DETAILS,MANAGE_DETAILS,REPORT,ORDER,BACK,LOGIN,MANAGE,RECEPTION;
}
